/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TextEditorRouteImport } from './routes/text-editor'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KbRouteImport } from './routes/kb'
import { Route as GtdRouteImport } from './routes/gtd'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsThemeRouteImport } from './routes/settings.theme'

const TextEditorRoute = TextEditorRouteImport.update({
  id: '/text-editor',
  path: '/text-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KbRoute = KbRouteImport.update({
  id: '/kb',
  path: '/kb',
  getParentRoute: () => rootRouteImport,
} as any)
const GtdRoute = GtdRouteImport.update({
  id: '/gtd',
  path: '/gtd',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsThemeRoute = SettingsThemeRouteImport.update({
  id: '/settings/theme',
  path: '/settings/theme',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gtd': typeof GtdRoute
  '/kb': typeof KbRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/text-editor': typeof TextEditorRoute
  '/settings/theme': typeof SettingsThemeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gtd': typeof GtdRoute
  '/kb': typeof KbRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/text-editor': typeof TextEditorRoute
  '/settings/theme': typeof SettingsThemeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gtd': typeof GtdRoute
  '/kb': typeof KbRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/text-editor': typeof TextEditorRoute
  '/settings/theme': typeof SettingsThemeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gtd'
    | '/kb'
    | '/login'
    | '/register'
    | '/text-editor'
    | '/settings/theme'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gtd'
    | '/kb'
    | '/login'
    | '/register'
    | '/text-editor'
    | '/settings/theme'
  id:
    | '__root__'
    | '/'
    | '/gtd'
    | '/kb'
    | '/login'
    | '/register'
    | '/text-editor'
    | '/settings/theme'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GtdRoute: typeof GtdRoute
  KbRoute: typeof KbRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  TextEditorRoute: typeof TextEditorRoute
  SettingsThemeRoute: typeof SettingsThemeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/text-editor': {
      id: '/text-editor'
      path: '/text-editor'
      fullPath: '/text-editor'
      preLoaderRoute: typeof TextEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kb': {
      id: '/kb'
      path: '/kb'
      fullPath: '/kb'
      preLoaderRoute: typeof KbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gtd': {
      id: '/gtd'
      path: '/gtd'
      fullPath: '/gtd'
      preLoaderRoute: typeof GtdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/theme': {
      id: '/settings/theme'
      path: '/settings/theme'
      fullPath: '/settings/theme'
      preLoaderRoute: typeof SettingsThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GtdRoute: GtdRoute,
  KbRoute: KbRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  TextEditorRoute: TextEditorRoute,
  SettingsThemeRoute: SettingsThemeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
