/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as SseRouteImport } from './routes/sse'
import { Route as SimpleRouteImport } from './routes/simple'
import { Route as HitlRouteImport } from './routes/hitl'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WeatherIndexRouteImport } from './routes/weather.index'
import { Route as WeatherSseRouteImport } from './routes/weather.sse'

const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const SseRoute = SseRouteImport.update({
  id: '/sse',
  path: '/sse',
  getParentRoute: () => rootRouteImport,
} as any)
const SimpleRoute = SimpleRouteImport.update({
  id: '/simple',
  path: '/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const HitlRoute = HitlRouteImport.update({
  id: '/hitl',
  path: '/hitl',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherIndexRoute = WeatherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WeatherRoute,
} as any)
const WeatherSseRoute = WeatherSseRouteImport.update({
  id: '/sse',
  path: '/sse',
  getParentRoute: () => WeatherRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hitl': typeof HitlRoute
  '/simple': typeof SimpleRoute
  '/sse': typeof SseRoute
  '/weather': typeof WeatherRouteWithChildren
  '/weather/sse': typeof WeatherSseRoute
  '/weather/': typeof WeatherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hitl': typeof HitlRoute
  '/simple': typeof SimpleRoute
  '/sse': typeof SseRoute
  '/weather/sse': typeof WeatherSseRoute
  '/weather': typeof WeatherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hitl': typeof HitlRoute
  '/simple': typeof SimpleRoute
  '/sse': typeof SseRoute
  '/weather': typeof WeatherRouteWithChildren
  '/weather/sse': typeof WeatherSseRoute
  '/weather/': typeof WeatherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hitl'
    | '/simple'
    | '/sse'
    | '/weather'
    | '/weather/sse'
    | '/weather/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hitl' | '/simple' | '/sse' | '/weather/sse' | '/weather'
  id:
    | '__root__'
    | '/'
    | '/hitl'
    | '/simple'
    | '/sse'
    | '/weather'
    | '/weather/sse'
    | '/weather/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HitlRoute: typeof HitlRoute
  SimpleRoute: typeof SimpleRoute
  SseRoute: typeof SseRoute
  WeatherRoute: typeof WeatherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sse': {
      id: '/sse'
      path: '/sse'
      fullPath: '/sse'
      preLoaderRoute: typeof SseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simple': {
      id: '/simple'
      path: '/simple'
      fullPath: '/simple'
      preLoaderRoute: typeof SimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hitl': {
      id: '/hitl'
      path: '/hitl'
      fullPath: '/hitl'
      preLoaderRoute: typeof HitlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather/': {
      id: '/weather/'
      path: '/'
      fullPath: '/weather/'
      preLoaderRoute: typeof WeatherIndexRouteImport
      parentRoute: typeof WeatherRoute
    }
    '/weather/sse': {
      id: '/weather/sse'
      path: '/sse'
      fullPath: '/weather/sse'
      preLoaderRoute: typeof WeatherSseRouteImport
      parentRoute: typeof WeatherRoute
    }
  }
}

interface WeatherRouteChildren {
  WeatherSseRoute: typeof WeatherSseRoute
  WeatherIndexRoute: typeof WeatherIndexRoute
}

const WeatherRouteChildren: WeatherRouteChildren = {
  WeatherSseRoute: WeatherSseRoute,
  WeatherIndexRoute: WeatherIndexRoute,
}

const WeatherRouteWithChildren =
  WeatherRoute._addFileChildren(WeatherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HitlRoute: HitlRoute,
  SimpleRoute: SimpleRoute,
  SseRoute: SseRoute,
  WeatherRoute: WeatherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
