/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TextEditorRouteImport } from './routes/text-editor'
import { Route as RscRouteImport } from './routes/rsc'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KbRouteImport } from './routes/kb'
import { Route as GtdRouteImport } from './routes/gtd'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AgentLabRouteImport } from './routes/agent-lab'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as SettingsThemeRouteImport } from './routes/settings.theme'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'

const TextEditorRoute = TextEditorRouteImport.update({
  id: '/text-editor',
  path: '/text-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const RscRoute = RscRouteImport.update({
  id: '/rsc',
  path: '/rsc',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KbRoute = KbRouteImport.update({
  id: '/kb',
  path: '/kb',
  getParentRoute: () => rootRouteImport,
} as any)
const GtdRoute = GtdRouteImport.update({
  id: '/gtd',
  path: '/gtd',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentLabRoute = AgentLabRouteImport.update({
  id: '/agent-lab',
  path: '/agent-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const SettingsThemeRoute = SettingsThemeRouteImport.update({
  id: '/settings/theme',
  path: '/settings/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-lab': typeof AgentLabRoute
  '/chat': typeof ChatRoute
  '/gtd': typeof GtdRoute
  '/kb': typeof KbRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/register': typeof RegisterRoute
  '/resources': typeof ResourcesRoute
  '/rsc': typeof RscRoute
  '/text-editor': typeof TextEditorRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-lab': typeof AgentLabRoute
  '/chat': typeof ChatRoute
  '/gtd': typeof GtdRoute
  '/kb': typeof KbRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/resources': typeof ResourcesRoute
  '/rsc': typeof RscRoute
  '/text-editor': typeof TextEditorRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-lab': typeof AgentLabRoute
  '/chat': typeof ChatRoute
  '/gtd': typeof GtdRoute
  '/kb': typeof KbRoute
  '/login': typeof LoginRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/register': typeof RegisterRoute
  '/resources': typeof ResourcesRoute
  '/rsc': typeof RscRoute
  '/text-editor': typeof TextEditorRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-lab'
    | '/chat'
    | '/gtd'
    | '/kb'
    | '/login'
    | '/projects'
    | '/register'
    | '/resources'
    | '/rsc'
    | '/text-editor'
    | '/projects/$id'
    | '/settings/theme'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-lab'
    | '/chat'
    | '/gtd'
    | '/kb'
    | '/login'
    | '/register'
    | '/resources'
    | '/rsc'
    | '/text-editor'
    | '/projects/$id'
    | '/settings/theme'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/agent-lab'
    | '/chat'
    | '/gtd'
    | '/kb'
    | '/login'
    | '/projects'
    | '/register'
    | '/resources'
    | '/rsc'
    | '/text-editor'
    | '/projects/$id'
    | '/settings/theme'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentLabRoute: typeof AgentLabRoute
  ChatRoute: typeof ChatRoute
  GtdRoute: typeof GtdRoute
  KbRoute: typeof KbRoute
  LoginRoute: typeof LoginRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResourcesRoute: typeof ResourcesRoute
  RscRoute: typeof RscRoute
  TextEditorRoute: typeof TextEditorRoute
  SettingsThemeRoute: typeof SettingsThemeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/text-editor': {
      id: '/text-editor'
      path: '/text-editor'
      fullPath: '/text-editor'
      preLoaderRoute: typeof TextEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rsc': {
      id: '/rsc'
      path: '/rsc'
      fullPath: '/rsc'
      preLoaderRoute: typeof RscRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kb': {
      id: '/kb'
      path: '/kb'
      fullPath: '/kb'
      preLoaderRoute: typeof KbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gtd': {
      id: '/gtd'
      path: '/gtd'
      fullPath: '/gtd'
      preLoaderRoute: typeof GtdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-lab': {
      id: '/agent-lab'
      path: '/agent-lab'
      fullPath: '/agent-lab'
      preLoaderRoute: typeof AgentLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/settings/theme': {
      id: '/settings/theme'
      path: '/settings/theme'
      fullPath: '/settings/theme'
      preLoaderRoute: typeof SettingsThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentLabRoute: AgentLabRoute,
  ChatRoute: ChatRoute,
  GtdRoute: GtdRoute,
  KbRoute: KbRoute,
  LoginRoute: LoginRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResourcesRoute: ResourcesRoute,
  RscRoute: RscRoute,
  TextEditorRoute: TextEditorRoute,
  SettingsThemeRoute: SettingsThemeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
